### ISSUE TITLE
TLUNotifier french localization not included

### ISSUE THREAD

**Issue by Emic37** [amaxwell/tlutility#101]
Hi, 
The new version 1.40 does not include the french localization for TLUNotifier. Can you add it in the next update ? 
Thanks in advance !

**Comment by amaxwell** [comment]
The files weren't part of the Xcode project, so I added them manually. Hopefully it works, but let me know either way.  https://github.com/amaxwell/tlutility/releases/download/1.41b1/TeX.Live.Utility.app-1.41b1.dmg

**Comment by Emic37** [comment]
Ok. Thanks. It works. Beautiful ! ;)
