### ISSUE TITLE
Two translation errors in German translation

### ISSUE THREAD

**Issue by martinantonmueller** [amaxwell/tlutility#104]
Aktualalisierung -> should be Aktualisierung

Aktualsieren -> should be Aktualisieren

<img width="829" alt="Bildschirmfoto 2021-01-19 um 08 23 46" src="https://user-images.githubusercontent.com/11441262/105001732-84549d80-5a30-11eb-8018-be814715b55d.png">

**Comment by amaxwell** [comment]
Thanks for the report. This appears to have been fixed by pull request #103.
