### ISSUE TITLE
[German translation] Translation error for "No Updates Available".

### ISSUE THREAD

**Issue by chrschmitz** [amaxwell/tlutility#105]
"No Updates Available" is currently translated to "Es sind keine Backups verfügbar". Correct would be " Es sind keine Aktualisierungen verfügbar".

Is it possible to help with the localization? I could not find anything.

BTW: The link to this website in the main help window is connected to http//amaxwell.github.io/tlutility/.

**Comment by amaxwell** [comment]
Thanks, fixed for the next release. To work on the translation, you modify the xibs and Localizable.strings file in the appropriate .lproj folder.
