### ISSUE TITLE
Generate DMG with HFS+ instead of APFS

### ISSUE THREAD

**Issue by EricFromCanada** [amaxwell/tlutility#111]
Since modern versions of macOS's `hdiutil` default to creating APFS-formatted disk images, I'd suggest that [this line](https://github.com/amaxwell/tlutility/blob/master/build_beta.py#L212) be updated to:
```
cmd = ["/usr/bin/hdiutil", "create", "-fs", "HFS+", "-srcfolder", BUILT_APP, temp_dmg_path]
```
so that an HFS+ image is created instead for backwards compatibility.

**Comment by amaxwell** [comment]
Thanks, that's not good at all, and I don't see it documented in the man page. APFS didn't even exist when I wrote that script, so it's nice to see Apple's typical attention to backwards compatibility at work.

**Comment by amaxwell** [comment]
Well, I can't actually run this on Big Sur, as it fails.
`$ hdiutil create -fs HFS+ -srcfolder /tmp/TLU-amaxwell/Release/TeX\ Live\ Utility.app /tmp/tlu.dmg
.....could not access /Volumes/TeX Live Utility/TeX Live Utility.app/Contents/MacOS/.BC.T_HqnKok - Operation not permitted

hdiutil: create failed - Operation not permitted
`

**Comment by amaxwell** [comment]
Fixed in latest release by switching to zip file. Thanks for the report.
