### ISSUE TITLE
OS X 10.11.6 El Capitan:  No mountable file systems

### ISSUE THREAD

**Issue by GMS103** [amaxwell/tlutility#112]
This happens on OS X 10.11.6 El Capitan, freshly installed on an empty disk.
After installing MacTeX 2018 (last compatible version), when trying to self-update TLU it downloads the latest version 1.47 and then gives an error.
Downloading manually the .dmg and trying to open it gives the error "no mountable file systems".
I have checked everything (extensions, login items, launch items, etc.) without success.
Of course, one can open the .dmg on a more recent OS and copy the app (everything is ok on macOS 10.13.6 High Sierra for instance).
I was wondering if somebody else was having this issue.

**Comment by amaxwell** [comment]
Sorry, this is fallout from https://github.com/amaxwell/tlutility/issues/111, which diskutil now makes APFS disk images by default. Unfortunately, I have not been able to copy the signed application to an HFS+ disk image, because Apple has somehow managed to break that in Big Sur.

**Comment by GMS103** [comment]
Thank you.
As a temporary workaround, perhaps you could make available the app as a zipped file?

**Comment by amaxwell** [comment]
Well, I used to use a zipped file, but Gatekeeper would frequently lie and tell you it was damaged and couldn't be opened. I changed it to a .dmg a year ago to work around that problem, so I'm not sure there's a good solution here.

**Comment by amaxwell** [comment]
Please let me know if this works. https://github.com/amaxwell/tlutility/releases/download/1.48b7/TeX.Live.Utility.app-1.48b7.zip

**Comment by GMS103** [comment]
Sorry for the delay.
Yes, it works on OS X 10.11.6 El Capitan.
Installing gpg fails (I could send you the log but I have been unable to find it).

**Comment by amaxwell** [comment]
You can copy rows from TLU's log window and paste the relevant part here or into an email. It saves the last few sessions.

**Comment by amaxwell** [comment]
Packaging issues fixed by switching to a zip file. If you have problems with gpg, please file a new report.
