### ISSUE TITLE
Ned a new mirror

### ISSUE THREAD

**Issue by quebrik3d** [amaxwell/tlutility#116]
I am currently using http://mirror.ctan.org/systems/texlive/tlnet as a source of updates.  It seems to no longer work.  How do I find a new mirror source for updates? Thanks.

**Comment by amaxwell** [comment]
What TeX Live version are you using?

**Comment by amaxwell** [comment]
Please choose "Log Window" from the Window menu, select all the output from the most recent failure, and copy and paste it here.

**Comment by quebrik3d** [comment]
I managed to fix it, or probably, its more accurate to say it fixed itself after upgrading to 1.49.  Suddenly, the error messages stopped and the updates resumed.  Thank you for your interest on my behalf.  I appreciate it.

Chip Pfister


W. Charles Pfister, MD, MBA, FCAP, FASCP

4333 Fifth Street
East Beach
St. Simons Island, GA, USA 31522

///snowboarder.happens.mural
31.05089° N. 81.37306° W.

+1 229-392-0703
***@***.*** ***@***.***>

Preserving the Oxford comma, one-at-a-time!
