### ISSUE TITLE
How to install external files such as the Springer Nature template (sn-jnl.cls)?

### ISSUE THREAD

**Issue by dreamplusplus** [amaxwell/tlutility#120]
Dear all,

I want to install the Springer Nature template (sn-jnl.cls) from 

https://www.springernature.com/gp/authors/campaigns/latex-author-support

I am using Tex Live Utility version 1.49 for maxOS Big Sur.

I couldn't find any way to do so. Is it possible? If yes, then how?

Thanks in advance and best regards

**Comment by amaxwell** [comment]
Springer needs to submit it to CTAN in a compatible license so that TeX Live will add it. If that happens, TeX Live Utility will install it.

**Comment by dreamplusplus** [comment]
Thanks for the response and best regards
