### ISSUE TITLE
TexLive updates fail with TexLive-2021 on OSX10.14.6 (tar argument list too long)

### ISSUE THREAD

**Issue by mjmeijer** [amaxwell/tlutility#121]
Using texlive GUI fails and resorting to terminal gives this:

$ sudo /usr/local/texlive/2021/bin/universal-darwin/tlmgr --repository https://mirror.koddos.net/CTAN/systems/texlive/tlnet --machine-readable --persistent-downloads update --all
Password:
start load https://mirror.koddos.net/CTAN/systems/texlive/tlnet
finish load https://mirror.koddos.net/CTAN/systems/texlive/tlnet
location-url	https://mirror.koddos.net/CTAN/systems/texlive/tlnet
total-bytes	494539381
end-of-header
**Can't exec "tar": Argument list too long at /usr/local/texlive/2021/tlpkg/TeXLive/TLUtils.pm line 686.**
/usr/local/texlive/2021/bin/universal-darwin/tlmgr: system(tar -cf /usr/local/texlive/2021/tlpkg/backups/noto.r54512.tar texmf-dist/doc/fonts/noto texmf-dist/fonts/enc/dvips/noto/nto_2banio.enc 
[ many lines ommtted to allow posting]
texmf-dist/fonts/vf/google/noto/NotoSerif-ThinItalic-tosf-t1.vf texmf-dist/fonts/vf/google/noto/NotoSerif-ThinItalic-tosf-ts1.vf texmf-dist/tex/latex/noto tlpkg/tlpobj/noto.tlpobj) failed in /usr/local/texlive/2021, status -1 at /usr/local/texlive/2021/tlpkg/TeXLive/TLUtils.pm line 690.

**Comment by mjmeijer** [comment]
On OSX 10.14.6 we fined:
`$ tar --version`
`bsdtar 2.8.3 - libarchive 2.8.3`

**Comment by amaxwell** [comment]
Thanks for the report. I've sent this to the TeX Live email list, as there's nothing I can do about it. As a workaround, you can manually select all packages except `noto` for update in TeX Live Utility.
