### ISSUE TITLE
Tex Live Utility fails to list updates

### ISSUE THREAD

**Issue by GHT54** [amaxwell/tlutility#122]
[](url
<img width="594" alt="Capture d’écran 2021-10-18 à 11 26 46" src="https://user-images.githubusercontent.com/22460040/137706318-e9f3c6f3-a725-4d42-badd-cd588c7071b6.png">
)
TeXShop 4.68
MacOS 10.14.6

**Comment by almansa** [comment]
Same problem as @GHT54, @geremiam here: 
My system is macOS 10.14.6.

I was using MacTex 2020 yesterday (Nov 13) and Tex Live Utility with the default repo (https://mirrors.ircam.fr/pub/CTAN/systems/texlive/tlnet/ for me) insisted with the "Listing Failed" error.
I installed the new MacTeX 2021 version this morning (Nov 14) hoping that it would solve the problem, but it didn't.

Then I came across this open issue, and I tried the solution suggested by @amaxwell to @geremiam.
However, unlike @geremiam, the solution did not work for me. I tried several mirrors (including  https://mirror.csclub.uwaterloo.ca/CTAN/systems/texlive/tlnet/ which worked for @geremiam) and they all produce the same "Listing Failed" error or this other error: "Unable to determine repository version".

I also looked at the macports solution pointed by @amaxwell :
https://trac.macports.org/wiki/ProblemHotlist#letsencrypt
It does explain the problem and how to solve it for all macOS systems except for macOS 10.13 and 10.14 which is my case.

So I still have no solution within macOS 10.14.
I could try to upgrade to macOS 10.15, 11 or 12 and follow the macports instructions if necessary.
But this is not possible in older machines which cannot be upgraded.

Please find enclosed the Tex Live Utility logs for the last two days:
[Tex Live Utility log.txt](https://github.com/amaxwell/tlutility/files/7534126/Tex.Live.Utility.log.txt)

Best regards,

AA

**Comment by amaxwell** [comment]
If you're willing to accept the security risk, you can try editing the URL in TeX Live Utility's address field to use http, rather than https. If the server allows it, that should work around the problem. If there are any ftp servers left, that would also work around the problem, since ftp isn't encrypted.

**Comment by amaxwell** [comment]
Hopefully 1.52 will take care of this. Please file a new report if not.
