### ISSUE TITLE
Server validation does not work 

### ISSUE THREAD

**Issue by ghost** [amaxwell/tlutility#125]
Hello all,
I recently updated the software and since then the validation no longer works for me under macOS 12.3 (beta) It only shows me this in the programme window, but the programme no longer reacts. 

What can I do? What is possibly wrong here?

**Comment by amaxwell** [comment]
The first thing you're doing wrong is telling me instead of Apple, since you're beta testing their crappy OS. However, the answer is that Apple sucks, and decided to remove Python in a minor update. Try the latest beta.

https://github.com/amaxwell/tlutility/releases/download/1.53b9/TeX.Live.Utility.app-1.53b9.zip

**Comment by ZXRobotum** [comment]
Thank you very much for your help.
But I sent any Information about this issue to APPLE too. But I know, that they need a long time to send me an feedback or solve that problem. So it was easier to send you this message too, because i work with LaTeX every day...

**Comment by ZXRobotum** [comment]
Good evening,
I just downloaded the download and tried it on a computer. But I still get the message that the server would be validated - but in the URL line no server is shown. When I manually enter a URL address, the program tells me that I have the latest version installed on my machine, but it again can't validate with the URL page (not installed yet).... Which repository - URL can I try with this?

**Comment by amaxwell** [comment]
This version should work with any repository, so I'll need to see the log output (see the Windows menu). You can select all rows, then copy and paste the log contents into a plain text file attachment or text box here.

**Comment by ZXRobotum** [comment]
Hello,
thank you very much for your help and I would like to write to today, that it´s work now.

After the Installation from your file and Update from macOS, now it´s work fine. Thank you so much....
