### ISSUE TITLE
Recurring background service notification on MacOS

### ISSUE THREAD

**Issue by mhooreman** [amaxwell/tlutility#135]
Hello,

@amaxwell , I'm really sorry, but I realize that it is a duplicated of #134 . Can you cancel this?

All my apologies...

---

Hello,

I have reinstalled TexLive from scratch and, a very limited time after that, I have a recurring message by MacOS saying that an element from "Adam Maxwell" has been added as background element (see screenshot below, in French - 3 notifications on the first 5 minutes after reboot, then calming down).

If I try to disable that service using MacOS configuration tool (‘General > Login Items’), it is re-enabled automatically.

When I disable automatic updates (e.g. set to "never") using TexLive's GUI options, the problem disappears (and the "Adam Maxwell" service is not anymore in the MacOS configuration tool.

Thanks a lot for your help,
Michaël

    michael@smith:~
    $ sw_vers
    ProductName:        macOS
    ProductVersion:     13.1
    BuildVersion:       22C65

    michael@smith:~
    $ tlmgr --version
    tlmgr revision 63068 (2022-04-18 07:58:07 +0200)
    tlmgr using installation: /usr/local/texlive/2022
    TeX Live (https://tug.org/texlive) version 2022

<img width="360" alt="Capture d’écran 2023-01-13 à 08 59 58" src="https://user-images.githubusercontent.com/7373718/212269491-20e23c7a-609b-4db6-b529-e3ebabdb9fed.png">

**Comment by amaxwell** [comment]
No apology necessary, and thanks for taking the time to make a report. This is a stupid and annoying problem that Apple has created, and the duplicate notification problem is a bug in Ventura that could be reported to Apple, if you care to waste the time. I just learned of a possible fix for the name problem, and will try to get a beta release out soon.
