### ISSUE TITLE
Configure documentation exits with error

### ISSUE THREAD

**Issue by marek-iiasa** [amaxwell/tlutility#139]
I use Tex Live Utility since many years, generally works OK and it is useful. Thank you! Now I run it on iMac M1 and onMacBook Air of 2014; I've just updated (on both machines) to Tex 2023; again, no problems. However, I've tried again (after last try in 2022) to run Configure documentation and this again resulted (after several hours of uploading files) in: Install failed. I attach the image of last few lines of the log-file.

Actually, I don't know, if I really need to configure the documentation because each installed package actually has its documentation, which appears to be updated whenever packages are updated. Therefore, maybe I simply should refrain from "Configure documentation"?

I guess that the problem might be caused by one of several migrations between machines and/or many updates. Therefore, I considered to remove all documentation and install it anew. However, I cannot figure out, where the documentation is stored (I don't keep any backups of the Tex Live Utility)

Thanks in advance for your comments on this issue.

With best wishes,
Marek Makowski

![Screenshot 2023-03-21 at 15 34 21](https://user-images.githubusercontent.com/17126375/226639792-3e7d65cc-0be4-46d4-8e61-8cdc5d0e0b83.png)

**Comment by amaxwell** [comment]
If you installed via MacTeX, you do not need to run this. The "Configure Documentation" option is for BasicTeX users, or anyone who installs without package documentation via the UNIX script, and later regrets that choice. See the Help book for more details.

**Comment by marek-iiasa** [comment]
Thanks for the clarification. Once more, many thanks for the MacTex: this makes the life of many TeX users **much** easier. 🙂
