### ISSUE TITLE
Packages backup

### ISSUE THREAD

**Issue by matteo339** [amaxwell/tlutility#141]
I just updated the packages of my TeXLive 2023 distribution.
Unfortunately, now, I am having problems with running my source codes and I don't know which package is causing the problem.

I would like to suggest that you add, in the `action menu`, the `Backup Selected Packages` and `Backup All Packages` items.

Matteo

**Comment by amaxwell** [comment]
That is not possible, because as far as I know, the underlying `tlmgr` tool does not offer that capability. If you have automatic backups enabled, previous versions of updated packages will appear in the Backups tab. For details, review the Help book.
