### ISSUE TITLE
Packages are displayed again and again - Although update „successful“

### ISSUE THREAD

**Issue by herry23xet** [amaxwell/tlutility#143]
I have updated all available packages today and the last few days. However, the packages are displayed again and again. And this although they should have been updated successfully. Also, the packages have a size of 0 kb. It also does not matter if I change the mirror. Always the same. I have the latest macOS version.
<img width="712" alt="Bildschirmfoto 2023-09-14 um 19 04 29" src="https://github.com/amaxwell/tlutility/assets/135629084/92b2c4f7-b661-4aae-a997-e0f82fa45e48">
<img width="712" alt="Bildschirmfoto 2023-09-14 um 19 04 39" src="https://github.com/amaxwell/tlutility/assets/135629084/5e813836-99a7-413d-94cd-f5dc2cdf95bd">
<img width="712" alt="Bildschirmfoto 2023-09-14 um 19 05 25" src="https://github.com/amaxwell/tlutility/assets/135629084/710b1841-1dc3-4e0e-aa4b-98bed4328f3e">

**Comment by amaxwell** [comment]
I recommend selecting those packages in the list and choosing "Reinstall Selected Packages" from the Actions menu. I think this can happen if there's an error downloading or installing, and tlmgr gets confused about its state.

**Comment by herry23xet** [comment]
Thank you! That helped! :)
