### ISSUE TITLE
no xz.[universal-darwin][.exe] binary for /usr/local/texlive/2023/bin/universal-darwin

### ISSUE THREAD

**Issue by GMS103** [amaxwell/tlutility#147]
Just to ask if this could be a transient error or not.
I tried my usual mirror and also the root server.
Logs attached. TIA,
Guillermo
[TLU fail 1.txt](https://github.com/amaxwell/tlutility/files/13400160/TLU.fail.1.txt)
[TLU fail 2.txt](https://github.com/amaxwell/tlutility/files/13400161/TLU.fail.2.txt)

**Comment by GMS103** [comment]
After doing
```sudo tlmgr update --self```
in a terminal, this issue seems to have disappeared.

**Comment by JuanCab** [comment]
I was having the critical update fail this morning regardless of the three mirrors I used.  The command line workaround you posted here DID work for me to get that critical update made.

**Comment by cportner** [comment]
Same here. Constant fails on the critical update but updating through the terminal worked. MacOS 14.1.1.

**Comment by GMS103** [comment]
Quoting Adam:

> The update-tlmgr-latest.sh script is currently broken on Macs, and the TeX Live team is investigating. If there's something you really need, you can update using command-line tlmgr.

https://email.esm.psu.edu/pipermail/macosx-tex/2023-November/058802.html

**Comment by GMS103** [comment]
Quoting Adam again:
> For the update junkies who don't want to use the command line: you can now do this in TeX Live Utility by holding down the option key and choosing "Install TeX Live Manager From Critical Repository" from the "Actions" menu.

https://email.esm.psu.edu/pipermail/macosx-tex/2023-November/058814.html

So I think this can be closed.
Thanks once more, Adam.

**Comment by amaxwell** [comment]
Thanks for the link. Reopening temporarily so hopefully people have more opportunity to find the solution, as I've been getting multiple reports a day on this tracker, three different mailing lists, and it even made it to stackexchange.

**Comment by GMS103** [comment]
Sorry for making you spend so much time on this.

**Comment by amaxwell** [comment]
It's not your fault, by any means. This was an extremely bizarre bug.
