### ISSUE TITLE
10.11 Developer Beta 1

### ISSUE THREAD

**Issue by flipphillips** [amaxwell/tlutility#15]
A heads-up-

According to the release notes for 10.11 beta 1:

	•	After upgrading to OS X v10.11 Developer Beta, applications that write to protected/system locations may no longer function correctly.

Indeed- it turns out the /usr/texbin directory can't be created / linked, even by root.
As a work-around, I've just linked texbin into /usr/local, which is still 'malleable', and re-directed my path there. However, I'm -guessing- this breaks texmgr and friends, since it expects /usr/texbin instead.

I haven't played extensively here enough (just installed the beta) to know any more specifics but am happy to report back what I figure out.

**Comment by amaxwell** [comment]
Not sure what you mean by texmgr (texdist?), but `tlmgr` will work fine as long as it's in your path, and TLU will work fine if you point it to `/usr/local/texlive/2015/bin/x86_64-darwin` or whatever full path. It'll be neat when everyone install 10.11 and /usr/texbin quits working, though.

**Comment by flipphillips** [comment]
whoops- yes- meant texdist sorry. Been on the road all day.
But- gonna be the usual cool OS ‘improvement' chaos!
Skim doesn’t work under this beta, also traditional.

Man-

-f

On Jun 8, 2015, at 9:34 PM, amaxwell <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what you mean by texmgr (texdist?), but tlmgr will work fine as long as it's in your path, and TLU will work fine if you point it to /usr/local/texlive/2015/bin/x86_64-darwin or whatever full path. It'll be neat when everyone install 10.11 and /usr/texbin quits working, though.

**Comment by tehabe** [comment]
The /usr is protected with El Capitan, so the texbin symlink is in /Library/TeX/texbin now, you have to change that in the TeX Live Utility. After that change, everything works just fine.

**Comment by aaronwolen** [comment]
Thanks @tehabe!

**Comment by amaxwell** [comment]
warning added in latest beta
