### ISSUE TITLE
Repository has a different TeX Live version

### ISSUE THREAD

**Issue by agl2015** [amaxwell/tlutility#18]
I am trying to update my 2015523 TeXLive installation with TeXLive Utility, and I get this mysterious error message:

Repository has a different TeX Live version
The repository at http://osl.ugr.es/CTAN/systems/texlive/tlnet has TeX Live 2015, but you have TeX Live 18446744073709551615 installed.  You need to switch repositories in order to continue.

I must tell that I don't have MacTeX, just a regular Unix-like TeXLive 2015 installation. But I have used TeXLive Utility for years with this set up, with no problems at all.

**Comment by amaxwell** [comment]
Likely the same as bug #17. See https://github.com/amaxwell/tlutility/issues/17#issuecomment-111517743 for a workaround; this was a TeX Live problem, not specific to MacTeX.
