### ISSUE TITLE
Tex Live Utility 1.21 issue

### ISSUE THREAD

**Issue by shouwei** [amaxwell/tlutility#19]
Hi there,

My OSX version is 10.10.4. I just upgraded MacTex to version 2015, and the embedded texlive version is 1.21. After installation, I run texlive trying to upgrade packages, but it keeps on "Validating Server..." for several hours. 
I don't know if any others has this problem.

**Comment by zhuzelong** [comment]
@shouwei  Please refer to the [issue 17](https://github.com/amaxwell/tlutility/issues/17) for the workaround. It seems a problem of MacTeX Live.

**Comment by shouwei** [comment]
@zhuzelong  Thank you so much! The workaround of creating a new text file do works for me.
