### ISSUE TITLE
Automatic updating msg pop-out

### ISSUE THREAD

**Issue by josdf** [amaxwell/tlutility#23]
Hey guys, just wanted you to fix the thing when someone install Tex Live Utility on OS X, on the second start-up it asks you if you want to have the program automatically updated, but if you agree with automatically updating, it doesnt do so.

Because when I head to Configure -> Schedule Tex Live Update checks then it's on "Never" and I have to manually set Daily/Weekly.

I have tested it on more than 1 mac computers.

**Comment by amaxwell** [comment]
This refers to automatic updating of TeX Live Utility itself (i.e., the program you're running). TeX Live update checking is for the contents of TeX Live.
