### ISSUE TITLE
Add warning about /usr/texbin on El Capitan

### ISSUE THREAD

**Issue by amaxwell** [amaxwell/tlutility#24]
Warn if running El Capitan and /usr/texbin is not present (if it's the default path). Prompt user to manually change the path.

**Comment by adunning** [comment]
The user is unlikely to know what path is required. Could it automatically switch to `/Library/TeX/texbin` (per the [document from MacTeX](https://tug.org/mactex/elcapitan.html)) if it isn't present, and only give a prompt if this is not present?

**Comment by amaxwell** [comment]
No, but I'll give the user the option to switch to the new path if it's present, so he won't have to know the location. As a matter of policy, I won't change user preferences automatically.

**Comment by amaxwell** [comment]
fixed in latest beta
