### ISSUE TITLE
Feature Request: Optionally Add Password to Keychain

### ISSUE THREAD

**Issue by ggodhner** [amaxwell/tlutility#26]
It would be helpful if you added the option (e.g., via a checkbox) on the login page to save the administrator password in the keychain.  I already know that I only run the *TeX Live Utility* when I intend to authorize it.  

Regards,

Geoff Odhner

**Comment by amaxwell** [comment]
This isn't possible; the system provides the dialog for your administrator password, and applications have no input to it. If you have a single user who will update TeX, I'd recommend you run `chown -R USER /usr/local/texlive` in Terminal where USER is your username (Get Info in Finder can probably do this, too). No more password prompts, and you avoid running my code and TeX Live Manager as root.
