### ISSUE TITLE
Default language seems to be Chinese

### ISSUE THREAD

**Issue by tweh** [amaxwell/tlutility#27]
Hi,

I just made the update to TeX Live 2015 (i.e. MacTeX) on OS X 10.9.5. The version of TeX Live Utility is 1.21. When I first started the App it was all in Chinese (my default language is german). Then I went to system preferences “Language & Region” (?), added English as a second language and restarted TeX Live Utility. Now it is in English which is fine.

Maybe you can make English the default instead of Chinese?!

Best,
Tobi

And btw. the Info pan shows the old Google Code URL …

**Comment by amaxwell** [comment]
Unfortunately, I can't do anything about the order of languages; picking a fallback language is entirely up to Apple, as far as I know. The info link has been fixed, thanks.
