### ISSUE TITLE
Formats not regenerated after update

### ISSUE THREAD

**Issue by adunning** [amaxwell/tlutility#28]
With a fresh installation of BasicTeX under OS X 10.11, formats were not recreated after the recent updates to LaTeX or Babel; `pdflatex` (etc.) was continuing to use version 2015/01/01 of the kernel and Babel 3.9l until I ran `fmtutil-sys --all` (after which it recognized the 2015/10/01 and 3.9m updates).

**Comment by amaxwell** [comment]
Not my bug; I just run tlmgr update commands and let it do all the work. It would be best to report this to the tex-live@tug.org mailing list.

**Comment by adunning** [comment]
Wasn't sure about that; thanks!

**Comment by amaxwell** [comment]
If @norbusan sees this, he might be able to comment here, especially if you have the log output from TLU (see the Window menu; that session should be saved).

**Comment by norbusan** [comment]
Hi
Indeed updates to the `babel` package do not trigger an update to the formats. I will look into it.

Updates to the `latex` package do trigger a rebuild, I just checked that.

**Comment by norbusan** [comment]
Ok, fixed in svn38566, will be in tomorrows tlcritical if you are interested. We will push out a tlmgr updated sooner or later.

**Comment by adunning** [comment]
Great; thank you very much! The LaTeX update definitely didn't trigger format recreation for me; happy to send you further details on this if required.

**Comment by norbusan** [comment]
Yes please, send me details. You can retrigger an update by editing the texlive.tlpdb file of your installation and refucing the revision line in the stanza that starts with `name latex`. Then run `tlmgr update --all -v` and send me the output per email. We should continue this discussion on the tex-live mailing list!!!

**Comment by adunning** [comment]
Done; thanks again!
