### ISSUE TITLE
prompting for system paper size (conditionals in pdftexconfig.tex since Oct 13, 2015)

### ISSUE THREAD

**Issue by jfbu** [amaxwell/tlutility#29]
Hi, since I upgraded to TLU 1.23 I systematically get a pop-up Warning on TLU's launch

    TeX Live paper size does not match system default

and I am asked if I want TLU to set it systemwide or ignore.
I am with TL2015, reasonably up-to-date.

If that helps here is what I get from tlmgr paper:

```
$ tlmgr paper
Current context paper size (from /usr/local/texlive/2015/texmf-dist/tex/context/user/cont-sys.rme): a4
Current dvipdfmx paper size (from /usr/local/texlive/2015/texmf-dist/dvipdfmx/dvipdfmx.cfg): a4
Current dvips paper size (from /usr/local/texlive/2015/texmf-dist/dvips/config/config.ps): a4
Current pdftex paper size (from /usr/local/texlive/2015/texmf-dist/tex/generic/config/pdftexconfig.tex): (undefined)
Current psutils paper size (from /usr/local/texlive/2015/texmf-dist/psutils/paper.cfg): a4
Current xdvi paper size (from /usr/local/texlive/2015/texmf-dist/xdvi/XDvi): a4
 ```

I don't know if this is relevant but `pdftexconfig.tex` from TL2015 has some added conditionals to check for LuaTeX.

If I switch back to TL2104, I get rather

```
$ tlmgr paper
Current context paper size (from /usr/local/texlive/2014/texmf-config/tex/context/user/cont-sys.tex): a4
Current dvipdfmx paper size (from /usr/local/texlive/2014/texmf-config/dvipdfmx/dvipdfmx.cfg): a4
Current dvips paper size (from /usr/local/texlive/2014/texmf-config/dvips/config/config.ps): a4
Current pdftex paper size (from /usr/local/texlive/2014/texmf-config/tex/generic/config/pdftexconfig.tex): a4
Current psutils paper size (from /usr/local/texlive/2014/texmf-config/psutils/paper.cfg): a4
Current xdvi paper size (from /usr/local/texlive/2014/texmf-config/xdvi/XDvi): a4
```

and TLU 1.23 then does not complain about system wide paper size setting.

About TL2015 I see now that `/usr/local/texlive/2015/texmf-dist/tex/generic/config/pdftexconfig.tex` has a last modified date of Oct. 13 (like `luatexiniconfig.tex`) which perhaps coincides more or less with the day when I updated TLU. Thus perhaps the issue has nothing do to with `TLU 1.23` per se.

Ah yes using Time Machine I see that earlier `pdftexconfig.tex` dated back to `May 14, 2010`. 

Perhaps the added conditionals  interfere with `TLU`'s parsing ?
best

**Comment by jfbu** [comment]
Actually, perhaps `TLU` relies on `tlmgr paper` thus the issue is more a `tlmgr` one which reports `undefined`. I will ask on TeX Live mailing list.
best
Jean-François

**Comment by jfbu** [comment]
I got confirmation that the issue is one of TeXLive which the maintainers have already fixed upstream:

http://tug.org/pipermail/tex-live/2015-October/037429.html

I have checked that the upgrade to `texlive.infra` soon to be pushed to `CTAN` indeed fixes the issue, which wasn't one of `TLU` after all.

**Comment by jfbu** [comment]
Last note: on another Mac OS X Mavericks machine, where I did not upgrade `tlmgr`, hence `tlmgr paper` still returns `undefined` for `pdftex`, well, `TLU 1.23` does not on launch prompt me for setting system wide the paper size default. Thus, there is something I do not understand.

Best wishes and thanks for `TLU`.

**Comment by amaxwell** [comment]
I use the first value from `tlmgr pdftex paper --list` and check the return value (so `echo $?`). Check TLU's log window for output of  `"System paper size = %@, pdftex paper size = %@", systemPaperSize, currentSize)` to see what it's returning.

**Comment by jfbu** [comment]
`tlmgr pdftex paper --list` gives
```
~$ tlmgr pdftex paper --list
(undefined)
a4
letter
```
(on the iMac where I did *not* update tlmgr itself from `tlcritical`)
and... wait... now TLU complains on this iMac too

    TeX Live paper size does not match system default

and the log window
```
2015-10-19 15:58:56 +0000 Notice -[TLMMainWindowController _paperSizeCheckTerminated:][8690]	System paper size = a4, pdftex paper size = (undefined)
```

I can't understand why I wasn't seeing this earlier today. Anyway, the bug is in `tlmgr` and has been fixed upstream. Once they push to `CTAN` the problem will disappear as it disappeared from my MBA after updating `tlmgr` directly from `tlcritical`.

**Comment by jfbu** [comment]
how silly I am: at 8AM this morning when I was testing TLU, 

    /usr/local/texlive/2015/texmf-dist/tex/generic/config/pdftexconfig.tex

was still the old one. Then I did a complete update, and only later in the day I launched TLU again. With the new `pdftexconfig.tex` with the conditionals `tlmgr` misbehaves, thus I suddenly saw the behavior. Best, Jean-François

**Comment by amaxwell** [comment]
There's really nothing I can do about this; if the TeX Live team pushes out files that are incompatible, that's just the way it is.
