### ISSUE TITLE
GUI problem in Mavericks

### ISSUE THREAD

**Issue by hmzppz** [amaxwell/tlutility#33]
In Mavericks, there is an issue with the GUI display: there are two black strips running around the header raw at the top of the package list. See the picture attached. There is no issue with El Capitan (I am not sure about Yosemiete). Also, the previous version 1.21 doesn't have this issue.
![screen shot 2015-11-08 at 5 24 46 pm](https://cloud.githubusercontent.com/assets/5751190/11023140/17803f46-863e-11e5-9714-f2ab54430c8f.png)

**Comment by amaxwell** [comment]
Please try the latest beta at https://github.com/amaxwell/tlutility/releases. I haven't changed anything with this table for years, so it must be due to Apple's latest Xcode release.

**Comment by jfbu** [comment]
> Please try the latest beta at https://github.com/amaxwell/tlutility/releases. I haven't changed anything with this table for years, so it must be due to Apple's latest Xcode release.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
Hi, 

the beta has not fixed the black strips problem signaled by hmzppz

I thought it was a deliberate design change !

I think I observed it first with 1.23 release.

best

Jean-François

**Comment by jfbu** [comment]
adding picture which was stripped from email it seems

![2015-11-09at08 46 36-cropped](https://cloud.githubusercontent.com/assets/2589111/11029073/801be416-86c4-11e5-9466-b0d84a0ce2fa.png)

**Comment by hmzppz** [comment]
1.24b2 doesn't fix it for me either.

Here is some additional information: clicking the tabs "Updates", "Packages", "Backups" temporarily removes the issue, but it comes back by moving the focus to another window and then again to TLU.

It is just a cosmetic issue, functionality is not affected, as far as I can tell.

**Comment by jfbu** [comment]
Indeed clicking the "Packages" or "Backups" tab seems to remove the issue but the black strips seem to temporarily have turned white; although sometimes they turn gray (but not always...) on clicking randomly on the variaous tabs. The black strips are also there in the Log window, and moving the focus to it and back to the main TLU window re-activate the black strips there, if they had been suppressed by the "tabs trick" of @hmzppz .

**Comment by hmzppz** [comment]
Apparently, this is no longer an issue with 1.26. Thanks!

**Comment by amaxwell** [comment]
I have absolutely no idea why this would be so, but I'm glad to hear it. Thanks!

**Comment by jfbu** [comment]
confirmed with 1.26 here too on 10.9.5 !
