### ISSUE TITLE
Alternative build options

### ISSUE THREAD

**Issue by Grieverheart** [amaxwell/tlutility#35]
Many users only install the Xcode command line tools instead of the beefy Xcode. It would be nice if there were alternative build options (e.g. via cmake) available to avoid having to install Xcode.

**Comment by amaxwell** [comment]
If the command-line tools include xcodebuild and ibtool, maybe that would work, but if you're doing development for OS X, you need Xcode and Interface Builder. There's just no way around that.

In addition, the dependency graph is already complicated, and includes multiple subprojects and targets; there's no way I'll ever tackle conversion to cmake, but feel free to submit a patch!
