### ISSUE TITLE
Optionally maintain a "TeXLive.library" file in ~/Library/FontCollections for XeTeX

### ISSUE THREAD

**Issue by jfbu** [amaxwell/tlutility#37]
OpenType fonts in `texmf-dist/fonts/opentype` are a bit cumbersome to access via XeLaTeX+fontspec. Exceptions are the fonts with accompanying packages (in `tex/latex`) contributed by Michael Sharpe as they come with foo.fontspec files:

```bash
texmf-dist$ find . -name '*.fontspec'
./tex/latex/baskervaldx/baskervaldx.fontspec
./tex/latex/erewhon/erewhon.fontspec
./tex/latex/fbb/fbb.fontspec
./tex/latex/heuristica/heuristica.fontspec
./tex/latex/inconsolata/Inconsolatazi4.fonatspec
./tex/latex/newpx/TeXGyrePagellaX.fontspec
./tex/latex/nimbus15/nimbusmono.fontspec
./tex/latex/nimbus15/nimbussans.fontspec
./tex/latex/nimbus15/nimbusserif.fontspec
./tex/latex/nimbus15/zco.fontspec
./tex/latex/nimbus15/zcoN.fontspec
./tex/latex/nimbus15/zhv.fontspec
./tex/latex/nimbus15/ztm.fontspec
./tex/latex/tempora/tempora.fontspec
./tex/latex/xcharter/XCharter.fontspec
```
Then the user can do `\setmainfont{erewhon}` for example without having to specify filenames not only for Regular but also Bold, Italic, BoldItalic.

For the other (the vast majority) of OpenType fonts, the usual recommendation is to copy them into one's `~/Library/Fonts`.

I experimented that `FontBook.app` has a concept of a "font library". The user creates the `<foo>` "font library" and adds fonts to it from arbitrary locations. The fonts are not moved but it seems the paths are stored into an xml file with simple structure in `~/Library/FontCollections` with name `<foo>.library`.

Once this is done with the TeXLive distributed OpenType fonts, using XeLaTeX becomes a breeze for accessing them.

However this has two issues:

1. One should keep in sync the FontBook library and the TeXLive `opentype/` data,

2. The FontBook.app appears very slow and unstable: it crashed multiple times my Mac OS Mavericks.

I was thus wondering if TLU could not provide an option "Create and maintain FontBook library `<TeXLive>` for using OpenType fonts easily via XeLaTeX". On each update via `TLU` changing something in `opentype`, the library file would get recreated  automatically by `TLU` with the hope that this is enough. Same for `texmf-local` hierarchy.

This would make using XeLaTeX much easier to use on Mac OS X with TeXLive fonts.

Alternative is to copy all fonts into one's home, but this has to be maintained  up-to-date. Besides duplicating possibly hundreds of megabytes is not an agreeable practice.

**Comment by amaxwell** [comment]
Sorry, there's no way I'll try to reverse-engineer their XML file. From a quick search, it doesn't appear documented at all.
