### ISSUE TITLE
Errors while updating packages

### ISSUE THREAD

**Issue by mpjdubois** [amaxwell/tlutility#39]
Hi Adam, I keep getting an error when I try to update my packages, and I can't figure out why. I am running the newest beta on el capitan (Path is set to /Library/TeX/texbin/). I attached a log from when I try to update. Cheers
[TLUlog_20_03.txt](https://github.com/amaxwell/tlutility/files/181463/TLUlog_20_03.txt)

**Comment by amaxwell** [comment]
It looks like some md5 checksum is failing when running http://mirror.utexas.edu/ctan/systems/texlive/tlnet/update-tlmgr-latest.sh

Error in MD5 checksums: 06ff2061fd5b78f0dbac7570bb4af051 is different from 7261c5ade112b5b0d43986d8aad29163

**Comment by mpjdubois** [comment]
I see, and is there any way for me to figure out on which files the MD5 checksum fails? Thanks

**Comment by amaxwell** [comment]
Hmm. I ran it manually and didn't see any failure; I wonder if something else on your system is triggering it?
`cd /tmp ; curl -O http://mirror.utexas.edu/ctan/systems/texlive/tlnet/update-tlmgr-latest.sh`
`sudo sh update-tlmgr-latest.sh`

**Comment by mpjdubois** [comment]
Yeah, is what I was afraid of. I'll have a look. Thanks anyway!

**Comment by amaxwell** [comment]
Sorry to not be more helpful; I can't reproduce it here. You might try posting to the tex-live mailing list, or we could tag @norbusan and see if he knows.

**Comment by norbusan** [comment]
@amaxwell, is this message `Error in MD5 checksums` coming from you? I don't find it in the sources we are running!

**Comment by norbusan** [comment]
Ahh, found it. That is code that is added by the `makeself` script. If you open the `update-tlmgr-latest.sh` with a text editor, you see it.

So the only explanation is that the downloaded copy, or the copy on the server got corrupted. 

@amaxwell when trying to update, is a cached copy used or re-downloaded every time? In case of a cached copy, this might be a bad download that is broken and needs redownloading. In this case the cache copy needs to be deleted manually.

**Comment by amaxwell** [comment]
Thanks, @norbusan! I originally thought it was my hash of `update-tlmgr-latest.sh`, but I use sha256. TLU does a new download each time, but it's possible that a proxy is caching a bad copy of it; it's probably easier to point TLU at a different TL mirror temporarily and update.

**Comment by norbusan** [comment]
I would be interested to get a copy of the wrong package, as well as from where it was downloaded.
