### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by BofMFa** [amaxwell/tlutility#44]
Hello,

Tex Live Utility version: 1.24
OS X 10.9.5 - Mavericks

I'm trying to update the tex repo, I get a problem with proxy. Instead of name@proxyserver:port, the request is password@proxyserver:port. And we can see in the log screen my proxy password. I had not this issue with the last version of tex live utility.

BofMFa

**Comment by amaxwell** [comment]
I haven't changed anything in the proxy code for years. All I can suggest is that you make sure you've entered the correct values in System Preferences.

**Comment by BofMFa** [comment]
I re-enter all system preferences and install new mactex, tex live does its job without problems, thanks. May be there was a problem with the system after the last Mac update.
