### ISSUE TITLE
Repository URL has a newer TeX Live version

### ISSUE THREAD

**Issue by NanoAkron** [amaxwell/tlutility#47]
Hi Adam,

I'm getting the following error with 1.24 and 1.25b1 on El Capitan:

Your TeX Live version is 2015, but your default repository URL appears to be for TeX Live 2016 etc etc...

I'm using the following repository:

http://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/texlive/tlnet

Hope there's a known or easy fix :)

**Comment by amaxwell** [comment]
Um, looking at the code, the "etc etc…" part that you trimmed should be

> You need to manually upgrade to a newer version of TeX Live, as there will be no further updates for your version.

If you want updates, you'll need to install TeX Live 2016, and the easiest way to do that is by installing MacTeX.

**Comment by NanoAkron** [comment]
Hi again,

That's exactly what I did in the first place and got that error message. It was then that I decided to pull down 1.24 and install it, but got the same error.The date on the file made me realise that was the same one that had been installed with MacTex 2016 so I installed 1.25b1 but still got the same error.

:(

I can try reinstalling TeX Live 2016, but I'm not quite sure if that'll change anything.

**Comment by amaxwell** [comment]
How did you install TeX Live 2016? If you did not install it using MacTeX, you probably need to adjust TeX Live Utility's path to point to the correct version of `tlmgr`. In TeX Live Utility's "Help," navigate to Features --> Preferences to see how to do this.

**Comment by NanoAkron** [comment]
So I've managed to fix the issue.

I had a lot of legacy versions installed right back to 2012. I removed them all from the command line, and all the symlinks etc.

I then reinstalled the MacTex 2016 distribution.

On opening TexLive Utility I got the error that I was using version 0. So I went into >Preferences and redirected the binaries to /usr/local/texlive/2016/bin/x86_64Darwin

Seems to work now.

**Comment by amaxwell** [comment]
If you installed via MacTeX, then you should be using `/Library/TeX/texbin` in TLU's preferences, and then next year you won't run into this problem again :). It sounds like you might not have gotten that change in TL 2015 due to an already customized pref.

**Comment by NanoAkron** [comment]
Cheers!
