### ISSUE TITLE
"listing failed" after update

### ISSUE THREAD

**Issue by jgclark** [amaxwell/tlutility#50]
I've just upgraded to the MacTeX 2016 release, and I can't get TeX Live Utility to do anything other than say "listing failed". 
I've downloaded the very large full installation, and installed all apart from Ghostscript. TeX Live Utility is v1.24. I've selected the "TeXLive-2016" distribution from the menu. I've tried 6 different Repositories, in different countries, and all of them give the same error message. I've tried a reboot, but no joy.
I'm sure this is something simple, but I can't see it.

**Comment by amaxwell** [comment]
Ensure that your path setting in preferences is correct. For MacTeX 2016, this would be /Library/TeX/texbin. If that isn't the problem, I'll need to see the log window output.

On Jul 11, 2016, at 03:09 PM, jgclark <notifications@github.com> wrote:

I've just upgraded to the MacTeX 2016 release, and I can't get TeX Live Utility to do anything other than say "listing failed". 
I've downloaded the very large full installation, and installed all apart from Ghostscript. TeX Live Utility is v1.24. I've selected the "TeXLive-2016" distribution from the menu. I've tried 6 different Repositories, in different countries, and all of them give the same error message. I've tried a reboot, but no joy.
I'm sure this is something simple, but I can't see it.

**Comment by jgclark** [comment]
Thanks, @amaxwell. That was the problem.

In my defence, and for the help of others, I'd seen the "TeX programs" setting in the preferences, but the space is narrow and was taken up with 5 blue folders, and I couldn't see the text. I also thought that it wasn't relevant as I was running the latest version of a TeX program, and it didn't seem to be setting repository or distribution.

**Comment by amaxwell** [comment]
Yeah, Apple's NSPathControl is really crappy, in spite of it being the only "approved" method of showing a path to users. Once someone modifies the setting to point inside `/usr/local/texlive`, it's pretty useless. On the other hand, the only time you should change the default is if you install via something other than MacTeX.

**Comment by jgclark** [comment]
I see.  Perhaps it's just me, but the labelling of the control didn't help me think it was relevant. Given I was already running what a layman would think of as a "TeX program", it's only after I saw your reply that I realised this was referring to the TeX binaries, not this GUI. I just wonder whether that could be either made clearer, or a start-up test run to see whether (particularly for El Capitan onwards) there are any binaries there, and if not, flagging an error to the user.

**Comment by amaxwell** [comment]
There is actually a check made during startup and a special warning for El Capitan and later. Regardless, it's logged, but there's no El Cap alert shown if the user has manually changed the path. In that case, the assumption is that the user knows what he's doing and will fix it, but that doesn't help when the user forgets :). I'll look into making a more general alert to flag this error.

Calling them binaries would help a subset of the population, but confuse others; I could change it to "TeX Live Manager" or "TeX Live programs." FWIW, the preference settings are all described in the Help book.

**Comment by amaxwell** [comment]
Reopen as a reminder for the alert.

**Comment by amaxwell** [comment]
Gruesome fix checked in.

**Comment by rbq** [comment]
Got the same error message, but for a different reason. According to the logs:

```
/Library/TeX/texbin/tlmgr: Initialization failed (in setup_unix_one):
/Library/TeX/texbin/tlmgr: could not find a usable wget.
/Library/TeX/texbin/tlmgr: Please install wget and try again.
```

Fixed it by `sudo ln -s /opt/local/bin/wget /Library/TeX/texbin/wget`.
