### ISSUE TITLE
TeX Live utility crashes when I hit the Backups tab

### ISSUE THREAD

**Issue by AthanasiusOfAlex** [amaxwell/tlutility#55]
I use version Version 1.30 (1.30) with TeX Live 2017.
MacBook, late 2014, running Mac OS X High Sierra.

When I try to open the Backups tab, TeX Live utility crashes.

Here is the crash report: https://pastebin.com/ra3myiJH

**Comment by amaxwell** [comment]
I'm leaning towards an Apple bug on this one, as I don't see anything wrong with the code, and it's been working for years. Since I don't have High Sierra yet, I can't reproduce it myself.

**Comment by amaxwell** [comment]
Try the latest beta here: https://github.com/amaxwell/tlutility/releases/download/1.31b1/TeX.Live.Utility.app-1.31b1.tar.gz

**Comment by amaxwell** [comment]
Cannot reproduce with current TLU and 10.13.2
