### ISSUE TITLE
Update texlive.infra fails

### ISSUE THREAD

**Issue by stoettner** [amaxwell/tlutility#57]
macOS 10.13.3
TexLive 1.3

Dear all,

on TexLive v1.3 the update of the critical package `texlive.infra` fails.

When using the terminal command `tlmgr update --self` it says:

```
tlmgr: package repository http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet (verified)
tlmgr: saving backups to /usr/local/texlive/2017/tlpkg/backups
/Library/TeX/texbin/tlmgr: create(tlpkg/tlpobj/texlive.infra.tlpobj) failed: 
Permission denied at /usr/local/texlive/2017/tlpkg/TeXLive/TLPOBJ.pm line 561.
```

Even when entering my user (admin rights) to the file TLPOBJ.pm the error message persists.

Any idea?

thanks,
wolf

**Comment by amaxwell** [comment]
If you use TeX Live Utility, it will prompt you for a password, if needed.

If you're using `tlmgr` manually in Terminal, you may need to prefix your commands with `sudo`, and you can ask the tex-live email list or http://tex.stackexchange.com for support.
