### ISSUE TITLE
TeX Live Utility failed to update packages

### ISSUE THREAD

**Issue by zpamaral** [amaxwell/tlutility#58]
Around early January 2018, TeX Live Utility (TLU) began failing to update packages. I updated to version 1.31b1 from 1.30 but that did not fix the problem. As a note, _sudo tlmgr update --all_ continued to work throughout and allowed me to keep the packages updated.

Today after looking at the log errors, I fixed the problem by:

1. _sudo ln -s /usr/local/bin/wget /Library/TeX/texbin/wget_ for TLU complained about not finding a functional wget. Again, I checked the logs and TLU does not inherit my complete _PATH_. I also

2. _sudo chmod a+r texlive.tlpdb_ for TLU complained about permission denied on that file. After making these two changes, TLU is able to to update packages.

Curiously, if I reinstall the TeX Live Manager, the file permissions revert to 600 from my modified 644. Therefore in summary, TLU is again working after I created a link to wget and added read permissions to texlive.tlpdb.

Any ideas about what the source problem might be? Thank you.

**Comment by amaxwell** [comment]
TLU is not supposed to inherit your PATH, by design. TeX Live ships with its own wget, so it sounds like your installation was corrupted somehow. You might want to reinstall MacTeX, unfortunately.

There have been problems with TL updates and permissions, but I thought those were resolved (and they weren't due to TLU, as far as I could tell). If you have changed your umask, there should be a message in TLU's log telling you about that problem.

**Comment by zpamaral** [comment]
Thank you for the prompt reply. I just reinstalled MacTeX. This seems to have fixed the wget problem but not the permissions problem. Tex Live Utility worked fine until I reinstalled the Tex Live Manager (I reinstalled it for testing purposes). Tex Live Manager will resume working if I change the permissions as described above.

**Comment by amaxwell** [comment]
I will take a look at this tonight. Can you provide step-by-step instructions on how to reproduce the problem you're seeing? I.e., what menu items you chose in TLU, and how you know it failed? Log output would also be helpful (see the Window menu); in particular, I need to know what repository you're using.

I have code to reset the permissions on the tlpdb to 644, but that only runs if it's not readable, as determined by -[NSFileManager isReadableFileAtPath:]. I'm not sure why that isn't being run in your case.

On Feb 08, 2018, at 09:56 AM, zpamaral <notifications@github.com> wrote:

Thank you for the prompt reply. I just reinstalled MacTeX. This seems to have fixed the wget problem but not the permissions problem. Tex Live Utility worked fine until I reinstalled the Tex Live Manager (I reinstalled it for testing purposes). Tex Live Manager will resume working if I change the permissions as described above.

**Comment by amaxwell** [comment]
I am not able to reproduce this, even using the same mirror URL. Can you reproduce the problem today?

**Comment by zpamaral** [comment]
Yes! I just did. I took some pictures of the main window and the log window.

![01 after starting](https://user-images.githubusercontent.com/36271736/36036710-8cdec3c4-0d88-11e8-8859-1485e0c2bc14.jpg)
Figure 1 — After starting the program for the first time this morning. I did not install any of the available updates.

![02 reinstall tex live manager](https://user-images.githubusercontent.com/36271736/36036748-a92ccf1c-0d88-11e8-827b-a67ce515af9e.jpg)
Figure 2 — Reinstalling the TeX Live Manager.

![03 reinstalled](https://user-images.githubusercontent.com/36271736/36036781-bec54fde-0d88-11e8-9064-17843f3e32af.jpg)
Figure 3 — Manager reinstalled.

![04 refresh package list](https://user-images.githubusercontent.com/36271736/36036802-cb238ec6-0d88-11e8-8180-d402981941ab.jpg)
Figure 4 — Refreshing package list.

![05 permissions problem](https://user-images.githubusercontent.com/36271736/36036837-eb1d9e10-0d88-11e8-92a3-3f505fa29552.jpg)
Figure 5 — Permissions problem shows up.

Then, I restarted the application and was prompted before any windows showed up to enter my administrator password (I guess so that the application could change the permissions on the file mentioned elsewhere).

![06 after restarting it works again](https://user-images.githubusercontent.com/36271736/36036912-2eb4b028-0d89-11e8-8dfb-f709c427fd29.jpg)
Figure 6 — After restarting and typing my administrator password, the application works again.

As a reminder, I only see this problem in High Sierra. I do have problems with neither El Capitan nor Sierra. I will try to install TLU 1.30 and see if this problem persists. Thank you.

**Comment by zpamaral** [comment]
TLU 1.30 shows the same behavior as described above.

**Comment by amaxwell** [comment]
Thanks, this is helpful, but I'm more baffled than before; your umask is correct. I tried this on High Sierra, and had no problems reinstalling TeX Live Manager and then installing some updates. Some random ideas, since I won't be able to look at this until tonight or tomorrow when I'm back at a Mac:

It's a lot to ask, but could you move aside `/usr/local/texlive` and reinstall MacTeX again? I wonder if there's some weird inherited permission problem.

Another shot in the dark: you could try moving aside ~/.wgetrc and trying again.

Final idea: try with an http repository; the tug ftp server is not the best one to use, because of connection limits on it.

**Comment by zpamaral** [comment]
> Thanks, this is helpful, but I'm more baffled than before; your umask is correct. I tried this on High Sierra, and had no problems reinstalling TeX Live Manager and then installing some updates. Some random ideas, since I won't be able to look at this until tonight or tomorrow when I'm back at a Mac:

You are welcome. I am looking forward to any suggestions or help.

> It's a lot to ask, but could you move aside `/usr/local/texlive` and reinstall MacTeX again? I wonder if there's some weird inherited permission problem.

Done and it did not work. I renamed texlive to texlive_old, reinstalled MacTeX from a fresh download, and was able to reproduce my problem by using the sequence above.

> Another shot in the dark: you could try moving aside ~/.wgetrc and trying again.

Done and it did nothing. I renamed my .wgetrc to .wgetrc_old, TLU no longer showed the prompt that a .wgetrc existed, but the problem persisted.

I also deleted TLU and all of its ancillary folders and files as detected by ApplCleaner, reinstalled TLU, and the same problem persisted.

> Final idea: try with an http repository; the tug ftp server is not the best one to use, because of connection limits on it.

http://mirror.hmc.edu/ctan/systems/texlive/tlnet/

Since testing the first suggestion above, I have switched to the URL above (I guess it is the default for I did not choose it).

Thank you for your help. This is an interesting problem.

**Comment by amaxwell** [comment]
Sorry for all the trouble on this. Here's one more idea to try:

Download and run the update-tlmgr-latest.sh script manually in Terminal, since that seems to be where things are going wrong:

cd /tmp
curl -O ftp://tug.ctan.org/tex-archive/systems/texlive/tlnet/update-tlmgr-latest.sh
sudo ./update-tlmgr-latest.sh --nox11

Info on it can be found here:

https://www.tug.org/texlive/tlmgr.html

This is how TLU updates TeX Live Manager. After running it in Terminal, use `ls -l` to manually check the permissions on the tlpdb file and see if you have read access. If this works, it points to a problem in TLU. If not, there's a problem in TL's update script.

**Comment by zpamaral** [comment]
If I run the script as instructed above, the reading permissions of texlive.tlpdb are changed from 644 to 600. Therefore, the script itself seems to elicit the problem. I hope this helps. This is the output from running the script:

Verifying archive integrity... All good.
Uncompressing TeX Live Manager Updater  100%
./runme.sh: updating in /usr/local/texlive/2017...
./runme.sh: tlmgr version says this is TeX Live 2017
./runme.sh: proceeding with tlmgr update.
./runme.sh: /Library/TeX/texbin/tlmgr including objects: master/tlpkg/tlpobj/texlive.infra.tlpobj master/tlpkg/tlpobj/texlive.infra.x86_64-darwin.tlpobj
D:tlmgr:main: ::tldownload_server defined: TeXLive::TLDownload=HASH(0x7fc105d5a5c8)
D:tl_tempdir: creating global tempdir /tmp/lK7Z_AiG2a
D:tl_tempdir: creating tempdir /tmp/lK7Z_AiG2a/AhXGn2L1L3
D:Using system wget (tested).
D:Using shipped /usr/local/texlive/2017/tlpkg/installer/xz/xzdec.x86_64-darwin for xzdec (tested).
D:Using shipped /usr/local/texlive/2017/tlpkg/installer/xz/xz.x86_64-darwin for xz (not tested).
./runme.sh: done.

Thank you.

**Comment by zpamaral** [comment]
Running the script from the CLI brought back the wget problem in TLU! I fixed it as described above with:

sudo ln -s /usr/local/bin/wget /Library/TeX/texbin/wget

The plot thickens.

**Comment by amaxwell** [comment]
At this point, I've emailed the TeX Live guys who understand update-tlmgr-latest.sh, since it really doesn't look like a TLU bug at this point (but I wouldn't rule out something screwy with High Sierra). Thanks again for all the tests here.

**Comment by zpamaral** [comment]
You are welcome. I am glad that I can now make TLU work, and with the wget problem “fixed” I can live with the occasional TLU restart. Thank you for your help, and if possible please keep me posted abut the TeX Live guys feedback.

**Comment by amaxwell** [comment]
From Karl Berry:

> Indeed, when I look at the beginning of update-tlmgr-latest.sh, I see
> umask 077. The makeself(1) program we use to generate the script had
> that hardwired into its header. Fortunately it has an option to use a
> different header, so I've committed a hacked version without the umask.

**Comment by zpamaral** [comment]
Success! I repeated the running of _update-tlmgr-latest.sh --nox11_ after I changed the umask from 077 to 022, and now it does not change the permissions on texlive.tlpdb! Nice. Thank you.

**Comment by zpamaral** [comment]
Hello,
Thank you.

> No dia 27 de mar de 2018, às 00:40, amaxwell <notifications@github.com> escreveu:
> 
> Closed #58.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

ZP
--
José Pedro Sousa do Amaral

Cynic, n.:
        A blackguard whose faulty vision sees things as they are, not as they ought to be.  Hence the custom among the Scythians of plucking out a cynic's eyes to improve his vision.
                -- Ambrose Bierce, "The Devil's Dictionary"
