### ISSUE TITLE
Should concertpass.com be a ctan mirror? 

### ISSUE THREAD

**Issue by paulromer149** [amaxwell/tlutility#62]
Today, Tex Live Utility tried to connect with an unfamiliar mirror, "concertpass.com." This seemed unusual. I expect only academic and non-profit hosts. 

One page shows that it is a mirror:

   https://ctan.org/mirrors/mirmon

I have attached a screen capture of the part of the page which lists it:

![image](https://user-images.githubusercontent.com/33130966/41503043-f5ee764e-7196-11e8-97f5-a8ea2a65c86b.png)

A second page does not:

  https://ctan.org/mirrors?lang=en#North%20America

If it is, indeed, a valid mirror, can you tell me what information, if any, this site might collect if Tex Live were to connect to it?

**Comment by amaxwell** [comment]
TeX Live Utility's mirror list is generated by parsing the CTAN sites list at Dante: 

http://dante.ctan.org/tex-archive/CTAN.sites

There are quite a few .com mirrors, including concertpass, and I have no idea what any of them collect from your http requests.
