### ISSUE TITLE
Support Touch ID for Authentication

### ISSUE THREAD

**Issue by dmzimmerman** [amaxwell/tlutility#66]
Minor feature suggestion:

Right now, TeX Live Utility accepts password authentication only. On MacBook Pros that support it, it would be very nice to be able to use Touch ID instead.

**Comment by amaxwell** [comment]
Sorry, the API for touch ID is not compatible with the authorization I need, as far as I can tell. In my opinion, the best fix is to change ownership of `/usr/local/texlive` to your local user and avoid running TeX Live Manager as root entirely.

**Comment by dmzimmerman** [comment]
That is... surprising, given that somebody implemented a version of `sudo` that uses Touch ID (https://github.com/mattrajca/sudo-touchid). 

I could of course change the ownership of /usr/local/texlive, but that'd be messing with the standard installation in a way that I'd rather not have to repeat every time I install a new version of TeXLive. 

It's fine; it was just something I thought would be nice to have. Maybe I'll implement it myself at some point and make a PR.

**Comment by dmzimmerman** [comment]
Understood. Thanks for the additional clarification!
