### ISSUE TITLE
Little Snitch complains about code signature

### ISSUE THREAD

**Issue by markr69** [amaxwell/tlutility#68]
Hi,
I use Little Snitch to monitor outgoing traffic from my Mac. Lately, whenever I want to launch TeX Live Utility it throws up a warning message about invalid code signature. Here is a screen shot of the pop up:
<img width="661" alt="screen shot 2018-08-20 at 11 33 22" src="https://user-images.githubusercontent.com/42537606/44333033-f1cdff80-a46d-11e8-829c-f4875b9d3b6c.png">
Any suggestion about what I should do? I love the functionality of TeX Live Utility, but being not knowledgeable about these issues involving code signature, I don't know what to do about this.
Thanks in advance for any help!
Best regards,
Martin Stokhof

**Comment by amaxwell** [comment]
I use a self-signed certificate, since I don't want to pay Apple $100 annually for the privilege of maintaining TeX Live Utility.

**Comment by markr69** [comment]
Dear Adam Maxwell,

Thanks very much for the quick reply. I understand the situation, and I am happy that  I can continue to use TeX Live Utility knowing that everything is ok.

Thanks for all the efforts in you put into developing and  maintaining this very useful piece of software for the benefit of the community of TeX users!

With kind regards,

Martin Stokhof
