### ISSUE TITLE
Add dark mode support for MacOS 10.14

### ISSUE THREAD

**Issue by dstansby** [amaxwell/tlutility#69]
It would be nice if a dark mode could be added for MacOS 10.14; see below for a small example of what Finder looks like in dark mode next to TexLive:

<img width="793" alt="screenshot 2018-09-27 at 21 08 19" src="https://user-images.githubusercontent.com/6197628/46171818-99262980-c299-11e8-9349-b26165eee2de.png">

**Comment by dstansby** [comment]
Great, thanks a lot!

**Comment by weitzner** [comment]
Any word on this?

**Comment by amaxwell** [comment]
Sorry, no. I haven't had time to install Mojave and experiment with this.

**Comment by amaxwell** [comment]
Should be working in the latest beta. https://github.com/amaxwell/tlutility/releases/download/1.37b9/TeX.Live.Utility.app-1.37b9.dmg
