### ISSUE TITLE
Tex Live 2019: Cannot update packages

### ISSUE THREAD

**Issue by kaelte** [amaxwell/tlutility#74]
I cannot update the packages of TexLive 2019 on macOS Mojave Version 10.14.5
﻿
<img width="1123" alt="Error Message" src="https://user-images.githubusercontent.com/10630145/59568347-bd20d980-9079-11e9-8bcf-6b9afcf4e7cb.png">

[TexLive_UpdateFailure.log](https://github.com/amaxwell/tlutility/files/3294475/TexLive_UpdateFailure.log)

**Comment by amaxwell** [comment]
My guess is that you're either out of disk space (unlikely) or using a different tar, since you're frobbing the PATH variable in /etc/launchd.conf.

**Comment by kaelte** [comment]
Thanks for your comment.

I have 138Gi of free disk space.

I do not know what _frobbing the PATH variable_ means. The file `/etc/launchd.conf` contains only one command: `setenv PATH "/usr/local/bin:...";`. However the variable `$PATH` in a terminal (bash) has a totally different value.

I did not use any Tarball. I have updated Texlive from 2018 to 2019 using MacTeX.pkg from this site: https://www.tug.org/mactex/.

I hope this additional info helps.

**Comment by amaxwell** [comment]
The update process is trying to unpack a tarball, and it's failing for some reason. I missed a key log entry:

`Recursive check completed in 10.6 seconds.  Root privileges not required.`

This looks like a permissions problem, and apparently my check is not adequate in your case. Can you post the output of `ls -ld /usr/local/texlive/` and `ls -l /usr/local/texlive/`? Did you manually change ownership of `/usr/local/texlive` after installing MacTeX?

**Comment by kaelte** [comment]
No, I did not change the ownership of `/usr/local/texlive`.
```
$ ls -ld /usr/local/texlive/
drwxr-xr-x  6 root  wheel  192 17 Jun 21:31 /usr/local/texlive/

$ ls -l /usr/local/texlive/
total 0
drwxr-xr-x  20 root  wheel  640  7 Mär  2018 2017
drwxr-xr-x  21 root  wheel  672 14 Mär 07:22 2018
drwxrwxr-x  20 root  wheel  640 17 Jun 21:32 2019
drwxr-xr-x   4 root  wheel  128 14 Mär 07:23 texmf-local
```

**Comment by amaxwell** [comment]
Interesting! Did you manually add group-writeable permission to the directory, or perhaps install it as a user with a different umask? The installer process doesn't run as group `wheel`, so this would fail; I'll have to think about how to handle this correctly.

As a workaround, you could try this, to remove the group-writeable bit.
`cd /usr/local/texlive && sudo chmod -R g-w 2019`

**Comment by amaxwell** [comment]
Hmm. I misread the code; I suspect this is still a permissions problem, but I'm not sure the change I suggested will help.

**Comment by kaelte** [comment]
I removed the group-writeable bit and now the update works. A bit difficult to understand that less privileges makes the programme to work. Or does the update explicitly refuses to work if permissions are too broad?

I cannot exclude that I have added the group-writeable bit: After updating Texlive to 2019 two months ago, the first updating packages failed with some permission denied error. But I do not remember what happend exactly and what I did two months ago. For some reason the package update has been working a few times.

Thanks for helping.

**Comment by amaxwell** [comment]
Apparently my check for permissions is not sufficient; sorry about that, and thanks for the help in finding the problem. Basically, I scan the texlive tree to see if I need to prompt the user to run the update process as root. I know it works if you recursively change ownership, but I never tested it with group permissions. 

Something odd is going on with group write permission on certain directories and MacTeX, as my own TL 2018 installation has mixed group-writeable permission on some directories, and I have no idea why. It doesn't have group-write permission for the files in those directories, though.
