### ISSUE TITLE
2019 updates fail from too long tar argument list

### ISSUE THREAD

**Issue by michaelaye** [amaxwell/tlutility#79]
My updates are currently failing at this step:

<img width="869" alt="Screen Shot 2019-12-23 at 11 27 02" src="https://user-images.githubusercontent.com/69774/71374218-26c4f780-2577-11ea-9a9c-15ac9ba9d76a.png">

Note that the text goes on forever, somehow looks like it lists all existing packages?
After that argument list, the log says:

<img width="857" alt="Screen Shot 2019-12-23 at 11 28 13" src="https://user-images.githubusercontent.com/69774/71374260-507e1e80-2577-11ea-8f19-32612f574838.png">

Note that the whole texlive folder is chown'ed by me, and the log file says correctly so:

```
2019-12-23 18:15:40 +0000 Notice -[TLMEnvironment _checkForRootPrivileges][79318]	Recursive check completed in 22.8 seconds.  Root privileges not required.
```
(Interestingly, the timestamp is changed in the clipboard, that might be because my system is using an international space standard for the date yyyy-mm-dd/jjj)

Please instruct on how to proceed.

**Comment by amaxwell** [comment]
Karl Berry gave a suggestion on how to possibly fix this using Terminal commands. It sounds like the TeX Live maintainers are still trying to figure out exactly what's going on.

https://tug.org/pipermail/tex-live/2019-December/044593.html

**Comment by michaelaye** [comment]
The terminal didn't work as described:
The force remove failed with the same error (tar argument list too long).
I then tried to solve it the other way around: I deleted all noto directories mentioned, then force removed the package, and then reinstalled it.
But I have a new error running TexLive. :(

```latex
! Latex Error: File `ltxcmds.sty' not found.
```

**Comment by amaxwell** [comment]
Wow, sorry I never responded on this one. I just realized that I was waiting for a fix from the TeX Live team, and probably forgot about it.
