### ISSUE TITLE
TeX-Live Utility has not found any updates for over two months

### ISSUE THREAD

**Issue by yrobbers** [amaxwell/tlutility#84]
My habit is to check for updates almost every day with TeX-Live Utility. Normally there are at least a few packages to update every day, and very rarely there is nothing to update at all. Since the third week of January, however, it has claimed that there are no updates available at all. I find that hard to believe, given past experience.

Today I found there was an updated version of TeX-Live Utility itself, which I installed. Despite an error this seems to have worked, but still no updated packages.

**Comment by amaxwell** [comment]
This is normal; TL 2019 is frozen, and will be receiving no further updates. TL 2020 is nearing release.
