### ISSUE TITLE
Build input file cannot be found: '/Users/josephliu/tlutility/fileview/English.lproj/FileView.strings'

### ISSUE THREAD

**Issue by drjosephliu** [amaxwell/tlutility#86]
Trying to install on Mac OS Catalina 10.15.4. When I hit build on Xcode, I get the following error:

Build input file cannot be found: '/Users/josephliu/tlutility/fileview/English.lproj/FileView.strings'

When I look in that folder though, I can see the `FileView.strings` file.

**Comment by amaxwell** [comment]
No idea what's going on with Xcode. See if anything at https://stackoverflow.com/questions/52401856/problems-after-upgrading-to-xcode-10-build-input-file-cannot-be-found helps.
