### ISSUE TITLE
NO connection to CTAN repo

### ISSUE THREAD

**Issue by micheld93** [amaxwell/tlutility#87]
Hi, 

I cannot use the ctan mirror "[(http://mirror.ctan.org/systems/texlive/tlnet)]" but I can use it via a browser. I got this message below but I tested 2 other mirrors where I got the message, that I'M using TL2019 and the version if the specific mirror cannot be determined. 

"Either a network problem exists or the TeX Live version on the server does not match.  If this problem persists on further attempts, you may need to try a different repository."

Are there any ideas?

Wishes,
Michel

**Comment by amaxwell** [comment]
There are no further updates available for TeX Live 2019. TeX Live 2020 was released this month, and all of the mirrors should be switched over to TL 2020 by now. If you need to install something from TL 2019, you can use ftp://ftp.tug.org/historic/systems/texlive/2019/tlnet-final.

**Comment by micheld93** [comment]
Thanks, I did forget that there is a new TL version. Thanks for the link.
