### ISSUE TITLE
MacOS10.15.5 Package "mercatormap" and "willowtreebook" cannot forcibly removed

### ISSUE THREAD

**Issue by yingpublic** [amaxwell/tlutility#91]
I am trying to download texlive utility under the latest macOS Catalina 10.15.5. However, the installation have been unsuccessfully for more than 5 times. 

Here are the screen I saw after I update everything
<img width="602" alt="Screen Shot 2020-06-01 at 1 43 14 PM" src="https://user-images.githubusercontent.com/7980467/83379474-2d04ad00-a40e-11ea-9fcf-d9fce7283006.png">

**Comment by amaxwell** [comment]
This generally indicates a problem during an update. Select the two forcibly removed packages and reinstall them, using the main menu or context menu.

**Comment by Claudio48** [comment]
I installed the latest TexLive utility and it runs under Catalina 10.15.5. However I am not able to update the packages. I always get the message "update failed"
