### ISSUE TITLE
Clarify manual install on website

### ISSUE THREAD

**Issue by HopeOneDayIWillType** [amaxwell/tlutility#95]
I am on Catalina 10.15.6

I downloaded the package via github and opened the TeX Live Utility project in xCode. When building I receive several certificate matching errors:

No certificate matching 'TeX Live Utility Signing Certificate' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.

----------------------------

Showing Recent Issues

Prepare build
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Using build description from memory

Build target tlu_ipctask of project TeX Live Utility with configuration Debug
error: No certificate matching 'TeX Live Utility Signing Certificate' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'tlu_ipctask' from project 'TeX Live Utility')

Build target TeX Live Utility of project TeX Live Utility with configuration Debug
error: No certificate matching 'TeX Live Utility Signing Certificate' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'TeX Live Utility' from project 'TeX Live Utility')

Build target Sparkle of project Sparkle with configuration Debug
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'Sparkle' from project 'Sparkle')

Build target DVI of project DVI with configuration Debug
error: No certificate matching 'TeX Live Utility Signing Certificate' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'DVI' from project 'DVI')

Build target relaunch tool of project Sparkle with configuration Debug
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'relaunch tool' from project 'Sparkle')

Build target DVIImporter of project DVIImporter with configuration Debug
error: No certificate matching 'TeX Live Utility Signing Certificate' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'DVIImporter' from project 'DVIImporter')
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'DVIImporter' from project 'DVIImporter')

Build target TLUNotifier of project TLUNotifier with configuration Debug
error: No certificate matching 'TeX Live Utility Signing Certificate' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'TLUNotifier' from project 'TLUNotifier')

Build failed    2020-08-27, 12:02 PM    0.1 seconds

**Comment by amaxwell** [comment]
If you want to build it from source, you need to create a signing certificate called "TeX Live Utility Signing Certificate" using Keychain Access (from the menu Keychain Access -> Certificate Assistant -> Create a Certificate…").

**Comment by amaxwell** [comment]
I'll also note that unless you want to modify the code, you're far better off running the latest release or beta. I have no idea if it even builds on Catalina, so you likely need some familiarity with Xcode as well, as I can't help with Catalina.

**Comment by HopeOneDayIWillType** [comment]
Hi, thanks for you answer. I actually did not find any alternative to building it from source. This is what I did:

I installed MacTex. There is a readme with "missing applications" where they say that given to certificate issues they can't include Tex Live Utilities in the package. They give a link to the website. I went on the website and I could not find a precompiled package, so I figured that the only way to have it install was by compiling it.

Sorry if I missed anything, but I would be seriously glad if there was an already compiled  version that I could run out of the box. Any link is super welcome.

**Comment by amaxwell** [comment]
Oh gosh, I'm sorry about that. I'll have to check that readme and see what link they used. I wondered why anyone would try building from source! 

The [home page](http://amaxwell.github.io/tlutility/) has a "Latest Release" link that should work, or you can get the latest beta by browsing [Tags](https://github.com/amaxwell/tlutility/tags). Github is a pretty confusing place to host binaries, unfortunately.

**Comment by HopeOneDayIWillType** [comment]
Hi thanks so much, I just downloaded it and everything seem to work fine.

It is probably obvious, and maybe I have been a bit dumb, but you might want add a sentence on the website saying that the latest dmg file is in the Latest Release section.

The problem was not in sthe "missing application file" which just gives the link:

This is the   "Missing Application" file:
Missing Applications; March, 2020 Catalina and Notarization
In Apple’s latest system Catalina, install packages must be notarized. Notarized packages are sent to Apple for confirmation that they contain no viruses. They are signed by a developer known to Apple, and during installation the system software checks that the package has not been altered since it was notarized.
All applications and command line programs in a notarized package must be signed by an Apple developer, timestamped, and adopt a hardened runtime.
Applications in MacTeX
MacTeX installs 159 command line programs from TEX Live. All of them have been signed and timestamped, and all adopt a hardened runtime.
MacTeX usually installs four GUI applications and one optional install package. These are TeXShop, TeX Live Utility, LaTeXiT, BibDesk, and cocoAspell. TeXShop and LaTeXiT meet the three conditions listed above. The remaining items have not been updated to meet these conditions, so it is impossible to include them in MacTeX. Below are addresses of their web sites, where further information is available and from which the applications can be downloaded.
Links
• TeX Live Utility https://amaxwell.github.io/tlutility/
• BibDesk https://bibdesk.sourceforge.io
• cocoAspell http://people.ict.usc.edu/~leuski/cocoaspell/
